name       : haskell-hspec-expectations
version    : 0.8.2
release    : 3
source     :
    - http://hackage.haskell.org/package/hspec-expectations-0.8.2/hspec-expectations-0.8.2.tar.gz : 819607ea1faf35ce5be34be61c6f50f3389ea43892d56fb28c57a9f5d54fb4ef
license    : MIT
component  : programming.haskell
summary    : Catchy combinators for HUnit
description: |
    Catchy combinators for HUnit
builddeps  :
    - haskell-cabal-install
    - haskell-HUnit-devel
rundeps    :
    - devel:
        - haskell-HUnit-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
